import { describe, expect, it } from "vitest";
import {
  validateLibrarySnapshot,
  verifyLibrarySnapshotChecksum,
} from "../../packages/integration/src";
import { buildLibrarySnapshot } from "./automationExport";
import type { OwnedGame, SteamCollection } from "./types";

function game(appid: number, name: string, playtime = 0): OwnedGame {
  return {
    appid,
    name,
    playtime_forever: playtime,
    img_icon_url: null,
    rtime_last_played: 0,
  };
}

function collection(key: string, name: string, added: number[]): SteamCollection {
  return {
    id: key,
    key,
    name,
    added,
    removed: [],
    timestamp: 1,
    is_deleted: false,
    is_dynamic: false,
  };
}

describe("Repressurizer integration package compatibility", () => {
  it("validates snapshots generated by the app exporter", () => {
    const snapshot = buildLibrarySnapshot({
      games: {
        1145360: game(1145360, "Hades", 120),
      },
      collections: [collection("favorites", "Favorites", [1145360])],
      appVersion: "0.2.0",
      generatedAt: "2026-06-18T18:00:00.000Z",
    });

    const result = validateLibrarySnapshot(snapshot, { verifyChecksum: true });

    expect(result.ok).toBe(true);
    expect(verifyLibrarySnapshotChecksum(snapshot)).toBe(true);
  });
});
